/**
 * Dr.Kit
 * this is mediio Dr.Kit api server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * it can be doctor or staff
 */

import { Field, InputType } from '@nestjs/graphql';
import { IsEmpty, IsNotEmpty } from 'class-validator';

@InputType()
export class ApplyUserDto {
  @Field({ nullable: false })
  @IsNotEmpty()
  id: string;

  @Field({ nullable: true })
  businessId?: string;

  @IsEmpty()
  email: string;

  @IsEmpty()
  encKey: string;
}
