/**
 * Dr.Kit
 * this is mediio Dr.Kit api server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Field, ID, InputType } from '@nestjs/graphql';
import { IsNotEmpty, MinLength } from 'class-validator';

@InputType()
export class CheckUserPwDto {
  @Field(() => ID, { nullable: false })
  @IsNotEmpty()
  id: string;

  @Field({ nullable: false })
  @IsNotEmpty()
  @MinLength(6)
  password: string;
}
