/**
 * Dr.Kit
 * this is mediio Dr.Kit api server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Field, InputType } from '@nestjs/graphql';
import { IsEmail, IsNotEmpty } from 'class-validator';

@InputType()
export class SendPwTokenEmailDto {
  // @Field({nullable: false})
  // @IsNotEmpty()
  // username: string;

  @Field({ nullable: false })
  @IsNotEmpty()
  @IsEmail()
  email: string;
}
