version: '3.8'

services:
  #  auth-server:
  #    build: spring-cloud/authorization-server
  #    image: manager/auth-server
  #    mem_limit: 350m
  #    networks:
  #      - my-network
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #      - SPRING_CONFIG_LOCATION=file:/config-repo/application.yml,file:/config-repo/auth-server.yml
  #      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USR}
  #      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PWD}
  #    volumes:
  #      - $PWD/config-repo:/config-repo
  mysql:
    image: mysql:8.0.23
    platform: linux/amd64
    restart: always
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dev-db
      - MYSQL_USER=lvtlvt2
      - MYSQL_PASSWORD=123456
      - MYSQL_NATIVE_PASSWORD=123456
    healthcheck:
      test: "/usr/bin/mysql --user=lvtlvt2 --password=123456 --execute \"SHOW DATABASES;\""
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - $PWD/dev-db/conf.d:/etc/mysql/conf.d
      - $PWD/dev-db/storage/mysql:/var/lib/mysql
#  redis:
#    image: "redis:alpine"
#    command: redis-server --requirepass 1234_567890_1234
#    ports:
#      - "6379:6379"
#    volumes:
#      - $PWD/redis-data:/var/lib/redis
#      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - REDIS_REPLICATION_MODE=master
